name: Deploy to Local IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Restore Packages
  	shell: cmd
  	run: dotnet restore IPOWeb.sln

      - name: Build Project
        shell: cmd
  	run: dotnet build IPOWeb.sln --configuration Release --no-restore

      - name: Publish Project
	shell: cmd
        run: dotnet publish IPOWeb.csproj --configuration Release --output "D:\Publish\ipoweb"

      - name: Stop IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "ipoweb"

      - name: Copy Files to IIS
        shell: powershell
        run: |
          Copy-Item "D:\Publish\ipoweb\*" "D:\inetpub\wwwroot\ipoweb" -Recurse -Force

      - name: Start IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "ipoweb"